INSERT INTO student_email (email_address)
VALUES
  ('facilisis.eget@hotmail.edu'),
  ('consectetuer.adipiscing.elit@protonmail.couk'),
  ('sed@icloud.couk'),
  ('egestas.duis@icloud.com'),
  ('sed.malesuada@hotmail.com'),
  ('consectetuer.adipiscing.elit@google.edu'),
  ('orci.consectetuer@aol.ca'),
  ('convallis.erat.eget@icloud.edu'),
  ('sit.amet@protonmail.ca'),
  ('donec.tincidunt.donec@protonmail.com'),
  ('sed.libero.proin@icloud.couk');
INSERT INTO student_email (email_address)
VALUES
  ('natoque.penatibus@icloud.net'),
  ('nisi@yahoo.com'),
  ('tellus.id.nunc@aol.com'),
  ('magna.sed.eu@icloud.org'),
  ('mauris.ipsum@yahoo.ca'),
  ('semper.cursus@google.com'),
  ('montes.nascetur@aol.ca'),
  ('eros.turpis.non@google.couk'),
  ('etiam.vestibulum.massa@protonmail.ca'),
  ('eget@google.net'),
  ('mauris@yahoo.edu');
INSERT INTO student_email (email_address)
VALUES
  ('nec.metus@hotmail.net'),
  ('parturient@yahoo.net'),
  ('vel@yahoo.org'),
  ('erat@protonmail.ca'),
  ('quam.curabitur@yahoo.net'),
  ('nulla.facilisi@aol.ca'),
  ('pellentesque.habitant@aol.com'),
  ('nec.tellus@aol.org'),
  ('mattis.integer@protonmail.ca'),
  ('nullam@yahoo.ca'),
  ('fusce.mi@yahoo.net');
INSERT INTO student_email (email_address)
VALUES
  ('donec.elementum@yahoo.com'),
  ('pede.sagittis.augue@yahoo.org'),
  ('felis.donec.tempor@aol.couk'),
  ('facilisis.magna.tellus@google.org'),
  ('metus@yahoo.net'),
  ('quis.turpis.vitae@yahoo.ca'),
  ('nostra.per@outlook.net'),
  ('amet.faucibus@outlook.couk'),
  ('neque.venenatis.lacus@yahoo.couk'),
  ('feugiat@aol.ca'),
  ('mauris.non@hotmail.ca');
INSERT INTO student_email (email_address)
VALUES
  ('et.arcu@icloud.org'),
  ('ornare.sagittis@icloud.ca'),
  ('rutrum.non@outlook.edu'),
  ('amet.risus@hotmail.com'),
  ('sagittis@protonmail.com'),
  ('gravida.molestie.arcu@outlook.edu');
INSERT INTO student_email (email_address)
VALUES
  ('pede@icloud.couk'),
  ('sem.semper@protonmail.couk'),
  ('ipsum.phasellus.vitae@aol.net'),
  ('sed.nulla@protonmail.com'),
  ('sed.tortor.integer@icloud.couk'),
  ('velit.aliquam.nisl@yahoo.couk'),
  ('vulputate.dui@outlook.com'),
  ('sed.diam@aol.couk'),
  ('ut@yahoo.couk'),
  ('sit@aol.org'),
  ('a.enim.suspendisse@yahoo.ca');
INSERT INTO student_email (email_address)
VALUES
  ('ac.orci@google.couk'),
  ('ipsum.suspendisse.sagittis@yahoo.com'),
  ('morbi.tristique@aol.com'),
  ('vivamus.rhoncus@google.couk'),
  ('pharetra.ut.pharetra@aol.couk'),
  ('sed@yahoo.org'),
  ('dolor.quisque@hotmail.com'),
  ('placerat.velit@icloud.ca'),
  ('et.eros@hotmail.net'),
  ('rhoncus.id.mollis@google.net'),
  ('tempor.erat.neque@yahoo.couk');
INSERT INTO student_email (email_address)
VALUES
  ('quisque.imperdiet@aol.com'),
  ('phasellus.fermentum@icloud.couk'),
  ('lorem@protonmail.net'),
  ('ipsum.dolor@protonmail.ca'),
  ('amet.consectetuer@hotmail.couk'),
  ('a.facilisis.non@protonmail.ca'),
  ('sem.magna@yahoo.couk'),
  ('non.dui@hotmail.couk'),
  ('vestibulum.accumsan.neque@icloud.net'),
  ('sem.egestas@aol.com'),
  ('mi.eleifend@protonmail.net');
INSERT INTO student_email (email_address)
VALUES
  ('enim.curabitur.massa@aol.ca'),
  ('tempus.risus.donec@outlook.org'),
  ('tincidunt.orci@icloud.couk'),
  ('non.quam@protonmail.com'),
  ('ac@hotmail.edu'),
  ('pharetra.ut@google.ca'),
  ('diam@outlook.ca'),
  ('mauris.eu@outlook.com'),
  ('nonummy.ut@outlook.ca'),
  ('velit.eu@outlook.couk'),
  ('id.sapien.cras@outlook.net');
INSERT INTO student_email (email_address)
VALUES
  ('nunc.sed.pede@yahoo.ca'),
  ('magna.sed.dui@google.com'),
  ('sociis.natoque@aol.edu'),
  ('non.enim@icloud.edu'),
  ('sem.ut@hotmail.ca'),
  ('gravida@icloud.edu');